spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://dpg-cn16oc8cmk4c73djfa40-a.oregon-postgres.render.com/database_jsvm
    username: database_jsvm_user
    password: XgqgdLJTnkcpMGc1XCbw4ys2U9zZGcUU
  flyway:
    baseline-on-migrate: true